# Generated by Django 5.2.1 on 2025-11-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='telefone',
        ),
        migrations.AddField(
            model_name='agenda',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='nome_completo',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
